"""API endpoints for transformation jobs."""

from typing import Annotated
from uuid import UUID

from fastapi import APIRouter, BackgroundTasks, Depends, HTTPException, status
from fastapi.responses import FileResponse
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import CurrentUser, get_current_user
from app.db.session import get_db
from app.api.v1.schemas.job import JobIssueResponse, JobResponse, ExportRequest, ExportResponse
from app.db.models.job import JobIssue, JobStatus, TransformationJob
from app.jobs.transformation import process_transformation_job
from app.jobs.export import process_export_job
from app.storage.local import LocalStorage

router = APIRouter(tags=["jobs"])


@router.post(
    "/projects/{project_id}/sources/{source_id}/jobs",
    response_model=JobResponse,
    status_code=status.HTTP_201_CREATED,
)
async def create_job(
    project_id: UUID,
    source_id: UUID,
    background_tasks: BackgroundTasks,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """Start a new transformation job for a data source."""
    
    # Check if a job is already running
    stmt = select(TransformationJob).where(
        TransformationJob.data_source_id == source_id,
        TransformationJob.status.in_([JobStatus.PENDING, JobStatus.RUNNING]),
    )
    result = await db.execute(stmt)
    existing_job = result.scalars().first()
    if existing_job:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="A job is already running for this data source.",
        )

    # Create new job
    job = TransformationJob(
        project_id=project_id,
        organization_id=current_user.organization_id,
        data_source_id=source_id,
    )
    db.add(job)
    await db.commit()
    await db.refresh(job)

    # Queue background task
    background_tasks.add_task(process_transformation_job, job.id)

    return job


@router.get("/projects/{project_id}/jobs", response_model=list[JobResponse])
async def list_jobs(
    project_id: UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """List all jobs for a project."""
    stmt = (
        select(TransformationJob)
        .where(
            TransformationJob.project_id == project_id,
            TransformationJob.organization_id == current_user.organization_id,
        )
        .order_by(TransformationJob.created_at.desc())
    )
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.get("/projects/{project_id}/jobs/{job_id}", response_model=JobResponse)
async def get_job(
    project_id: UUID,
    job_id: UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """Get status of a specific job."""
    job = await db.get(TransformationJob, job_id)
    if not job or job.organization_id != current_user.organization_id:
        raise HTTPException(status_code=404, detail="Job not found")
    return job


@router.get("/projects/{project_id}/jobs/{job_id}/issues", response_model=list[JobIssueResponse])
async def get_job_issues(
    project_id: UUID,
    job_id: UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """Get issues/errors generated by a job."""
    job = await db.get(TransformationJob, job_id)
    if not job or job.organization_id != current_user.organization_id:
        raise HTTPException(status_code=404, detail="Job not found")

    stmt = select(JobIssue).where(JobIssue.job_id == job_id).order_by(JobIssue.row_index)
    result = await db.execute(stmt)
    return list(result.scalars().all())


@router.get("/projects/{project_id}/jobs/{job_id}/download")
async def download_job_output(
    project_id: UUID,
    job_id: UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """Download the generated NDJSON file."""
    job = await db.get(TransformationJob, job_id)
    if not job or job.organization_id != current_user.organization_id:
        raise HTTPException(status_code=404, detail="Job not found")

    if job.status != JobStatus.COMPLETED or not job.output_file_path:
        raise HTTPException(status_code=400, detail="Job is not completed yet or no output generated.")

    storage = LocalStorage()
    target_path = storage._resolve_path(job.output_file_path)

    if not target_path.exists():
        raise HTTPException(status_code=404, detail="File not found on disk.")

    return FileResponse(
        target_path,
        media_type="application/x-ndjson",
        filename=f"fhir_output_{job_id}.ndjson",
    )


@router.post("/projects/{project_id}/jobs/{job_id}/export", response_model=ExportResponse)
async def export_job_output(
    project_id: UUID,
    job_id: UUID,
    request: ExportRequest,
    background_tasks: BackgroundTasks,
    db: Annotated[AsyncSession, Depends(get_db)],
    current_user: Annotated[CurrentUser, Depends(get_current_user)],
):
    """Export the completed job output to a target FHIR server."""
    job = await db.get(TransformationJob, job_id)
    if not job or job.organization_id != current_user.organization_id:
        raise HTTPException(status_code=404, detail="Job not found")

    if job.status != JobStatus.COMPLETED or not job.output_file_path:
        raise HTTPException(status_code=400, detail="Job is not completed yet or no output generated.")

    # Queue export task
    background_tasks.add_task(
        process_export_job, 
        job_id=job.id, 
        target_url=request.target_url, 
        auth_token=request.auth_token, 
        bundle_type=request.bundle_type
    )

    return {"status": "accepted", "message": "Export job has been queued in the background."}
