"""add mapping rules

Revision ID: 79b21aa27cba
Revises: 002
Create Date: 2026-06-12 00:59:05.041231
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '79b21aa27cba'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mapping_rules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('source_field', sa.String(length=255), nullable=False),
    sa.Column('target_fhir_field', sa.String(length=255), nullable=False),
    sa.Column('transformation_type', sa.String(length=50), nullable=False),
    sa.Column('transformation_config', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mapping_rules_data_source_id'), 'mapping_rules', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_organization_id'), 'mapping_rules', ['organization_id'], unique=False)
    op.create_index(op.f('ix_mapping_rules_project_id'), 'mapping_rules', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mapping_rules_project_id'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_organization_id'), table_name='mapping_rules')
    op.drop_index(op.f('ix_mapping_rules_data_source_id'), table_name='mapping_rules')
    op.drop_table('mapping_rules')
    # ### end Alembic commands ###
