"""add_masking_type

Revision ID: 911634c83d00
Revises: 9fa115a2d4a7
Create Date: 2026-06-13 01:34:00.678816
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '911634c83d00'
down_revision: Union[str, None] = '9fa115a2d4a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_rules', sa.Column('masking_type', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_rules', 'masking_type')
    # ### end Alembic commands ###
