"""add jobs

Revision ID: 919ad19a3e4e
Revises: 79b21aa27cba
Create Date: 2026-06-12 02:32:50.044189
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '919ad19a3e4e'
down_revision: Union[str, None] = '79b21aa27cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transformation_jobs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='job_status', create_constraint=True), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('processed_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('output_file_path', sa.String(length=1000), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transformation_jobs_data_source_id'), 'transformation_jobs', ['data_source_id'], unique=False)
    op.create_index(op.f('ix_transformation_jobs_organization_id'), 'transformation_jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_transformation_jobs_project_id'), 'transformation_jobs', ['project_id'], unique=False)
    op.create_table('job_issues',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('issue_type', sa.Enum('warning', 'error', name='issue_type', create_constraint=True), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['transformation_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_issues_job_id'), 'job_issues', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_issues_job_id'), table_name='job_issues')
    op.drop_table('job_issues')
    op.drop_index(op.f('ix_transformation_jobs_project_id'), table_name='transformation_jobs')
    op.drop_index(op.f('ix_transformation_jobs_organization_id'), table_name='transformation_jobs')
    op.drop_index(op.f('ix_transformation_jobs_data_source_id'), table_name='transformation_jobs')
    op.drop_table('transformation_jobs')
    # ### end Alembic commands ###
