"""Add value_map

Revision ID: 9fa115a2d4a7
Revises: 919ad19a3e4e
Create Date: 2026-06-12 03:36:07.201999
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9fa115a2d4a7'
down_revision: Union[str, None] = '919ad19a3e4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mapping_rules', sa.Column('value_map', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mapping_rules', 'value_map')
    # ### end Alembic commands ###
